### ISSUE TITLE
Sharing of resources feature?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/resourceful#1]
@ahdinosaur @donlewi Hi! Would you be interested in including sharing of resources at some point?  (I don't know of any immediate needs.  Just wanted to park the idea here for your consideration some day.)

There might be a lot of different use cases for this, car share, etc.  The one I have some familiarity with is when Sensorica (an open value network we work with) wanted to move into a new space with other maker type networks, and implement an app so they could share equipment between networks.  This never happened, and the app never happened either.  But we did a bit of initial requirements definition, which I could find. 

A key feature was access rules for a resource, defined by the owner or custodian of the resource.  Like certain people, certain projects, certain training required, others.

**Comment by ahdinosaur** [comment]
> we did a bit of initial requirements definition, which I could find.

the more information on use cases the better. :)

**Comment by fosterlynn** [comment]
> the more information on use cases the better. :)

Will do so when / if you get to shared resources...  :)

**Comment by danalexilewis** [comment]
@fosterlynn great that you add this - short answer is absolutely something to be included in the future. Either in this app or in one that builds on it.

A use case I always use is my folks house. They live on a grove where the grove has land in common, a trailer and now 30 pest control traps. It has always been my dream to take this to the next level and start to co-purchase certain items. eg an atmospheric water condenser and generator/wind-turbine. Giving you water and electricity in a disaster. The cost of these is prohibitive when you simply dont need them most of the time. As group its a one off purchase of a couple of hundred bucks.

One of the barriers to doing this is the management and transparency required takes too much time and so people won't buy in, because to do so requires trust - which is lacking. People don't trust each other because they don't need too/have too. So its a catch 22: people would trust each other more if they had more meaningful interaction with each other, people would have more meaningful interaction with each other if they trusted each other more.

To break this cycle we need better tools. This is the trajectory I see resourceful going in.

At the moment the roadmap is to just make something that works locally on your resources. Stage two will be to implement some sort of exchange and permissions system, which would allow for sharing/co-ownership of resources. (this is where it starts to get fun!)

**Comment by fosterlynn** [comment]
@donlewi  great use case!  All in good time.  :)

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/resourceful/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
