### ISSUE TITLE
How to read the Resourceful specs?

### ISSUE THREAD

**Issue by bhaugen** [valueflows/resourceful#2]
The link from the readme is a 404:
https://github.com/valueflows/resourceful/blob/master/features

And it's checkbox is not checked. Which I assume means, not implemented yet. Which is ok.

I can also find individual specs like this:
https://github.com/valueflows/resourceful/blob/master/specification/backend_app/user/resources/create_resource.feature

But I assume the intent is to have an overview/table of contents/navigation thingie? 

Any way I can help with this? I'd like to learn a little Cucumber.

**Comment by ahdinosaur** [comment]
hey @bhaugen, i think @agentlewis was using [featurebook](https://github.com/SOFTWARE-CLINIC/featurebook)

**Comment by bhaugen** [comment]
So do I need to clone resourceful and install featurebook and run the featurebook procedure and then I'll get something readable?

[edit: p.s. that's ok with me.]

**Comment by danalexilewis** [comment]
@bhaugen added some quick instructions to the readme. also noted that the features are broken as the spec requirements of featurebook were changed 3 months ago. added an [issue](https://github.com/valueflows/resourceful/issues/3). also noting that since i started this project cucumber.js has come leaps and bounds so have created a ticket to migrate from featurebook to it.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/resourceful/-/issues/2.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
